import './globals.css';
import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';

const noto_sans = Noto_Sans({
    variable: '--noto-sans-font',
    weight: ['300', '400', '500', '700'],
    style: ['normal'],
    fallback: ['sans-serif'],
    subsets: ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext'],
    preload: true,
    display: 'swap',
    });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang='ru'>
      <body className={noto_sans.className}>{children}</body>
    </html>
  );
}
