import './../(site)/globals.css';
import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import styles from './../(site)/layout.module.css';
import { Header } from '@/components/Header/Header';
import { Footer } from '@/components/Footer/Footer';
// import { Sidebar } from '@/components/Sidebar/Sidebar';


const noto_sans = Noto_Sans({
    variable: '--noto-sans-font',
    weight: ['300', '400', '500', '700'],
    style: ['normal'],
    fallback: ['sans-serif'],
    subsets: ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext'],
    preload: true,
    display: 'swap',
    });

export const metadata: Metadata = {
  title: 'Create Next App - LOGIN',
  description: 'Generated by create next app',
};

export default function LoginLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang='ru'>
      <body className={noto_sans.className}>
      <div className = { styles.wrapper }>
        <Header className = { styles.header } />
        <div>АВТОРИЗАЦИЯ!!!!!!!!!!!!!!!!!!</div>
            <div className = { styles.body } >
                {children}
            </div>
        <Footer className = { styles.footer } />
     </div></body>
    </html>
  );
}